version: '3.5'
services:
  code-server:
    image: mandarinkb/code-server:1.0.0
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      # - TZ=Etc/UTC
      - TZ=Asia/Bangkok
      # - PASSWORD=password #optional
      # - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=mandarinkb #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      # - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /config:/config
      - /config:/data
      - /config:/datago
    ports:
      - 8443:8443
    restart: unless-stopped
